version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      react:
        patterns:
          - "react"
          - "react-*"
      vite:
        patterns:
          - "vite"
          - "vite-*"
          - "@vitejs/*"
      eslint:
        patterns:
          - "eslint"
          - "eslint-*"
          - "@eslint/*"
      semantic-release:
        patterns:
          - "semantic-release"
          - "@semantic-release/*"
      linting-formatting:
        patterns:
          - "prettier"
          - "eslint-config-prettier"
          - "eslint-plugin-prettier"
          - "lint-staged"
          - "husky"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
