export const experiences = {
  sonraifull: {
    company: 'Sonrai Security',
    role: 'Software Engineer',
    location: 'Fredericton, New Brunswick',
    date: 'May 2025 - Present',
    link: 'https://sonraisecurity.com',
    points: ["Working on Sonrai's Cloud Permissions Firewall"],
    techs: ['Go', 'Java', 'Python', 'AWS', 'Auth0'],
  },
  harvest: {
    company: 'University of New Brunswick',
    role: 'Embedded Design Student Developer',
    location: 'Fredericton, New Brunswick',
    date: 'January 2025 - April 2025',
    link: 'https://www.unb.ca/',
    points: [
      'Developed and designed a cross-platform desktop application for UNB Harvest Competition with real-time monitoring, scoring, and cloud integration for 20+ rovers',
      'Built serverless backend architecture using AWS Lambda and S3 for data persistence',
      'Integrated custom serial protocol for real-time data acquisition from competition hardware',
      'Implemented CI/CD workflows for automated multi-platform deployment (Windows/macOS/Linux)',
    ],
    techs: ['JavaScript', 'Electron JS', 'Python', 'Flask', 'AWS', 'Zappa'],
  },
  sonrai2024: {
    company: 'Sonrai Security',
    role: 'Junior Software Engineer Co-op',
    location: 'Fredericton, New Brunswick',
    date: 'May 2024 - August 2024',
    link: 'https://sonraisecurity.com',
    points: [
      'Optimized batch discovery service by refining exception handling to prevent improper data invalidation',
      'Collaborated with an enterprise customer to optimize Azure AD collection performance, reducing collection time for an environment containing over 700,000 users and groups',
      'Served as a key resource for collection services, supporting team members with implementation and technical troubleshooting',
      'Implemented service monitoring by migrating metrics from Prometheus to New Relic',
    ],
    techs: [
      'Go',
      'Java',
      'SQL',
      'NoSQL',
      'Docker',
      'Kubernetes',
      'CircleCI',
      'AWS',
      'GCP',
      'Azure',
      'Agile',
      'Prometheous',
      'GraphQL',
    ],
  },
  sonrai2023: {
    company: 'Sonrai Security',
    role: 'Junior Software Engineer Co-op',
    location: 'Fredericton, New Brunswick',
    date: 'January 2023 - August 2023',
    link: 'https://sonraisecurity.com',
    points: [
      'Handled customer feature requests, driving the integration and support of AWS, Azure, and Google Cloud Platform services into the product',
      'Collaborated closely and played an active role with product management and design to ensure development and timely release of new features',
      "Addressed and resolved high-priority bugs from customers, ensuring the product's reliability and consistent performance",
    ],
    techs: ['Java', 'JavaScript', 'Linux', 'Docker', 'Kubernetes', 'AWS', 'GCP', 'Azure', 'Agile'],
  },
  cedar: {
    company: 'Cedar Groves Golf Course',
    role: 'Full Stack Developer',
    location: 'Saint John, New Brunswick',
    date: 'December 2022 - April 2023',
    link: 'https://cedargrovesgolf.ca',
    points: [
      'Designed and developed a full-stack website for Cedar Groves Golf Course, bringing their brand to life online and helping them reach a wider audience',
      'Implemented content management system allowing staff to easily update course information and seasonal hours of operation',
      'Deployed and actively maintain website infrastructure on AWS',
    ],
    techs: [
      'HTML',
      'CSS',
      'Bootstrap',
      'jQuery',
      'Node.js',
      'JavaScript',
      'Express.js',
      'AWS',
      'Docker',
      'CircleCI',
    ],
  },
}
